wandb/terraform-aws-wandb

README.md, modules/app_lb/variables.tf, variables.tf
- Uses the more restrictive ELBSecurityPolicy-FS-1-2-Res-2020-10 to only support TLS 1.2 and not 1.1/1.0.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#tls-security-policies
=> Use ELBSecurityPolicy-FS-1-2-Res-2020-10 for load balancers

README.md, modules/app_lb/variables.tf, variables.tf
We do not want to inadvertently increase attack surface, especially for self-managed deployments. This PR defaults inbound CIDR blocks to `[]` for both the load balancer and the EKS API. What might be a better UX is to not have a default and ensure the user enters their own CIDR block.
=> Do not allow any connections inbound by default

.gitignore, examples/byob/main.tf, examples/public-dns-with-route53/variables.tf, main.tf, modules/app_eks/main.tf, modules/app_eks/variables.tf, modules/networking/main.tf, modules/networking/outputs.tf, modules/networking/variables.tf, modules/redis/main.tf, modules/redis/outputs.tf, modules/redis/variables.tf, modules/redis/versions.tf, outputs.tf, variables.tf
Jira 
https://wandb.atlassian.net/browse/WB-7810
Adds a redis module so that we can externalize the filemeta queue. There are some other prs here that are prerequisites to making this possible
1. [Allow using redis connection string for filemeta queue](https://github.com/wandb/core/pull/8623)
2. [Add redis var to wandb terraform](https://github.com/wandb/terraform-kubernetes-wandb/pull/1)
I've tested the redis module and tested that the output can be passed to wandb local. I still need to test deploying my local branch in AWS using the external redis instance for the filemeta queue to make sure there are no connection/network issues.
=> [WB-7810] Add Redis Module

main.tf, modules/app_eks/variables.tf, modules/networking/main.tf, modules/networking/variables.tf, modules/redis/main.tf, modules/redis/variables.tf
Skip creating the elasticache subnet if we aren't provisioning an elasticache instance
=> fix: Skip creating elasticache subnet if it is disabled

modules/redis/main.tf
[Using inline security group rules in the `aws_security_group` resource along with the standalone `aws_security_group_rule` resource causes conflicts when the terraform is applied and rules to be overwritten](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group). This pr separates the rules out into their own resources.
=> fix: Separate redis security group rules

modules/database/main.tf
The result of this change would look like the following for **_existing_** installs:
```
Terraform will perform the following actions:
- resource "aws_appautoscaling_policy" "this" {
- arn                = "arn:aws:autoscaling:us-west-1:618469898284:scalingPolicy:5be523c8-270f-4165-bd79-042418491195:resource/rds/cluster:disable-auto-scale:policyName/target-metric" -> null
- id                 = "target-metric" -> null
- name               = "target-metric" -> null
- policy_type        = "TargetTrackingScaling" -> null
- resource_id        = "cluster:disable-auto-scale" -> null
- scalable_dimension = "rds:cluster:ReadReplicaCount" -> null
- service_namespace  = "rds" -> null
- target_tracking_scaling_policy_configuration {
- disable_scale_in   = false -> null
- scale_in_cooldown  = 300 -> …
```
=> feat: Disable auto scaling for database

modules/redis/main.tf
https://wandb.atlassian.net/browse/WB-12639
=> fix: Security ElastiCache.1

modules/app_lb/main.tf
Separating SG rule creation so that rules for http and https are created in two separate groups. This side-steps the quota on max # of SG rules per SG.
=> fix: Separate HTTP and HTTPS rule creation

modules/app_lb/main.tf
Reverts wandb/terraform-aws-wandb#90
=> fix: Revert separate HTTP and HTTPS rule creation

examples/byob/README.md, examples/public-dns-external/main.tf, examples/public-dns-external/variables.tf, main.tf, modules/app_eks/main.tf, modules/app_eks/variables.tf, modules/app_lb/main.tf, modules/app_lb/outputs.tf, modules/secure_storage_connector/main.tf, variables.tf
This to allow us to workaround the AWS quotas on max # of rules per security group (100).
=> fix: Put rules for inbound HTTP/HTTPS into their own security groups

examples/byob/main.tf
This pull request enables a customer to directly grant access to the EKS node role are removes the need for /root at the account level.
=> feat: Support team level buckets by using the direct node role ARN

examples/public-dns-external/versions.tf, examples/public-dns-with-route53/versions.tf, modules/app_lb/versions.tf, modules/database/versions.tf, modules/kms/versions.tf, modules/networking/versions.tf, modules/redis/versions.tf, modules/secure_storage_connector/versions.tf, variables.tf, versions.tf
This upgrades the AWS provider to version 4. *This is a breaking change.* Before upgrading to this version, be sure you have upgraded to v1.16.10. 
Additionally, the variable `database_performance_insights_kms_key_arn` variable has been provided a default value of `null`. This results in the default KMS key being used for Performance Insight metrics.
=> feat!: AWS Provider Upgrade

README.md, examples/public-dns-external/main.tf, examples/public-dns-external/variables.tf, main.tf, modules/app_eks/iam-policy-docs.tf, modules/app_eks/iam-roles.tf, modules/app_eks/variables.tf, modules/file_storage/main.tf, modules/file_storage/outputs.tf, modules/redis/main.tf, modules/secure_storage_connector/outputs.tf, variables.tf
This update addresses: 
- deprecated attributes in the app_eks, redis, and secure_storage modules
-  inline s3 bucket policies have been replaced with corresponding resource attachments, namely `aws_s3_bucket_acl`, `aws_s3_bucket_cors_configuration`, `aws_s3_bucket_ownership_controls`, `aws_s3_bucket_public_access_block`, and `aws_s3_bucket_server_side_encryption_configuration`
- outdated README: the required AWS provider version has been upgraded; section on upgrading kubernetes version in EKS has been expanded
- the default version of EKS has been set to `1.25` in both the repository root and in the  `app_eks` module. neither sets a default or allows a `null` value, which relegates the definition of the kubernetes version used in the EKS cluster explicitly to the invocation of the …
=> feat: Update provider deprecations

modules/networking/main.tf
This updates the VCP provider to version 4.0. This is necessary in preparation for upcoming updates to our RDS and EKS providers.
=> feat: Update vcp provider

variables.tf
This is a small change that updates the default instance type in the root module's variables to `m5.large`.
=> feat: Change default instance type

examples/byo-vpc-eks/README.md, examples/byo-vpc-eks/main.tf, examples/byo-vpc-eks/variables.tf
A few of customers in the past have requested to modify our terraform to allow provisioning resources into existing VPC and EKS clusters. This template helps with setting it up.
For context, customer who have asked for this in the past:
- DoorDash Labs
- Apple
- DIU
=> feat(examples): Adds tf template for bring your own vpc and eks

modules/app_eks/main.tf
This removes the EKS addon defined in the terraform in favor of using the Helm chart.
=> feat: Remove vpc-cni EKS add-on in app_eks/main.tf

examples/private-access-only/main.tf, examples/private-access-only/variables.tf, examples/private-access-only/versions.tf
fix: Fix private access example
=> fix: Fix private access example

modules/app_eks/main.tf, modules/app_eks/variables.tf, variables.tf
This PR updates the launch templates to use EBS `gp3` volume types.
=> fix: Switch to gp3 volumes on EKS nodes

examples/public-dns-external/main.tf, modules/app_eks/efs.tf
This PR fixes the EFS logic when subnets don't already exist.
=> fix: EFS index vs subnet for_each

README.md, main.tf, modules/private_link/main.tf, modules/private_link/variables.tf, variables.tf
This pull request introduces a p`rivate_link module` to enable to automatic setting up AWS PrivateLink. 
The key variable is `private_link_allowed_account_ids`, which triggers the module only when a list of allowed AWS account IDs is provided. 
Other crucial variables include `namespace` for resource naming (and the limit of LB's names), `network_private_subnets` for specifying VPC private subnets and `deletion_protection` for enabling deletion protection.
=> feat: PrivateLink support

deployment-size.tf, examples/byo-vpc-eks/main.tf, examples/byo-vpc-eks/variables.tf, examples/public-dns-external/main.tf, examples/public-dns-external/variables.tf, main.tf, modules/app_eks/variables.tf, outputs.tf, variables.tf
This PR continues work done by @kimjyhello to enable standardization of resource sizes across EKS node, RDS instance, and Elasticache node types.
=> feat: Add standardized instance sizing in AWS

examples/public-dns-external/main.tf, examples/public-dns-external/variables.tf, main.tf, modules/app_eks/main.tf, modules/app_eks/variables.tf, variables.tf
This PR enables setting the `system-reserved` flag as part of `kubelet_extra_args` when creating the node pool.  The default will not set the flag, but setting any of the 4 related variables will modify the extra args.  This requires a launch template to be created so that flag is an `or` with the encryption flag.
=> chore(dev): Add system-reserved option for node pool creation

examples/public-dns-external/main.tf, examples/public-dns-external/variables.tf, main.tf, modules/app_eks/iam-roles.tf, modules/app_eks/lb_controller/controller.tf, modules/app_eks/lb_controller/variables.tf, modules/app_eks/main.tf, modules/app_eks/variables.tf, variables.tf
Add `defaultTags` to the AWS LB controller which defaults to just adding `namespace`
Add `aws_loadbalancer_controller_tags` variable to allow for additional default tags.
Tested with `nigel-test-perceive` cluster, ALBs get proper tags in the default and extra scenarios.
=> chore(backend): Add 'defaultTags' for AWS LB controller

deployment-size.tf
Increase the deployment size for small, medium, and large to 3 nodes to account for kafka requirements
=> feat(backend): Make minimum nodes for t-shirts '3'

modules/app_eks/external_dns/external_dns.tf
Default is "1m", but we are hitting API rate limiting.
=> fix(deployer): Update external_dns interval

examples/public-dns-external/main.tf, modules/app_eks/add-ons.tf, modules/app_eks/main.tf
This PR changes the default version of EKS to 1.26. It also installs the AWS VPC-CNI add-on, and creates an IAM role for that add-on. If you find appying fails because some of the add-ons already exist, remove the add-ons in question using the AWS console or the AWS CLI and re-apply.
=> feat: Set default EKS to 1.26; install vpc-cni add-on

NOTICE, deployment-size.tf
This changes the node count from 3 for all sizes to 2, except xlarge and xxlarge.
=> fix: Amend standard sizes

modules/app_eks/add-ons.tf
```
Error: creating EKS Add-On (wandb-qa-aws:vpc-cni): ResourceInUseException: Addon already exists. { RespMetadata: { StatusCode: 409, RequestID: "c38e4e71-d773-42f6-8f27-164471b732bf" }, Message_: "Addon already exists." }
```
=> chore: Replace deprecated resolve conflicts field

main.tf, modules/kms/main.tf, modules/kms/outputs.tf, modules/kms/variables.tf, variables.tf
=> fix: Don't create KMS key and related resources for CH by default

modules/kms/main.tf
Fixes the conditional expression that controls whether we create `aws_kms_grant.clickhouse`
=> fix: Condition to create kms.aws_kms_grant.clickhouse was incorrect

main.tf
This is a fix for customers using SSE Encryption.
=> fix: Use bucket KMS key arn if provided for W&B managed bucket, always use that key even if empty for customer provided buckets

README.md, examples/public-dns-external/main.tf, examples/public-dns-external/variables.tf, main.tf, outputs.tf, variables.tf
```
~ resource "helm_release" "wandb" {
id                         = "wandb-cr"
~ metadata                   = [
- {
...
- values         = jsonencode(
{
- name = "wandb"
- spec = <<-EOT
"values":
"app": {}
"global":
"bucket":
"kmsKey": "arn:aws:kms:us-west-2:770934259321:key/c88a4da3-aabd-4265-a57d-e4f0115d04b8"
"name": "levin-aws-subpath-testing-file-storage-unbiased-chimp"
"path": ""
"provider": "s3"
"region": "us-west-2"
"cloudProvider": "aws"
...
EOT
}
)
- version        = "0.1.0"
},
] -> (known after apply)
name                       = "wandb-cr"
- set {
- name  = "spec" -> null
- type  = "string" -> null
- value = <<-EOT
"values":
"app": {}
"global":
"bucket":
"kmsKey": "arn:aws:kms:us-west-2:770934259321:key/c88a4da3-aabd-4265-a57d-e4f0115d04b8"
"name": …
```
=> feat: Add optional path var for instance level bucket path

examples/byob-sse-s3/README.md, examples/byob/README.md, modules/secure_storage_connector/README.md
How to create/configure BYOB is now in the public docu. I updated the Readmes to point to the public docu.
=> fix: Improve BYOB Readme

README.md
Customer Managed Encryption Keys for databases requires additional KMS key actions in the the policy. Particularly `kms:CreateGrant`. This PR updates the documented KMS key policy to include this action in the README.md.
=> fix: Adding CreateGrant to KMS key actions in KMS key policy for CMEK

main.tf, variables.tf
Adds a new variable kubernetes_cluster_oidc_issuer_url variable, and a local variable defining the weave trace server service account name. These two values are used to set the internalJWTMap value in our helm charts which defines the mapping of subject to issuer, which is used to authenticate internal service communication
=> feat: Add internalJWTMap variables used for inter service request authentication

main.tf, modules/file_storage/main.tf, modules/file_storage/variables.tf, modules/networking/main.tf, modules/networking/variables.tf, variables.tf
Added a boolean flag to enable or disable VPC Flow Logs. Default is set to disable.
Configured VPC Flow Logs to log REJECTED traffic only, focusing on denied network activity for enhanced security and compliance.
Implemented a feature to enforce the rejection of HTTP traffic for S3 buckets. This is also an optional feature.
=> feat: Add VPC flow logs option + s3 https-only policy

main.tf, modules/networking/main.tf, modules/networking/variables.tf, variables.tf
If a user disables VPC Flow Logs, the associated s3 bucket which stores these logs will be force deleted.
=> fix: S3 bucket force destroy

main.tf, modules/networking/main.tf, modules/networking/variables.tf
Option to deny HTTP traffic on S3 bucket containing VPC Flow Logs
=> fix: S3 https-only

modules/networking/main.tf
Exception for VPC service to send logs to s3 bucket via HTTP
=> fix: S3 https-only policy for VPC Flow Logs bucket
