- main.tf
- modules/kms/main.tf
- modules/kms/variables.tf
- variables.tf
Allows us to update the policy easily in situations when this error occurs https://app.terraform.io/app/weights-and-biases/workspaces/deployer-32b9f38e-925c-45ae-8aa8-9b83e6547260/runs/run-9vxdkUEzBgm16LUB
https://wandb.atlassian.net/browse/WB-7813
> feat(kms): Make kms key customizable

- README.md
- examples/public-dns-external/main.tf
- main.tf
- modules/app_eks/main.tf
- modules/app_eks/variables.tf
- variables.tf
Adds an option to update EKS cluster version via tf variable
> chore: Upgrade EKS cluster version

- modules/app_eks/main.tf
https://wandb.atlassian.net/browse/WB-12594
> fix: Deploy the aws-ebs-csi-driver so 1.23 k8s upgrade is possible

- CHANGELOG.md
- modules/app_eks/main.tf
https://wandb.atlassian.net/browse/WB-12607
> fix: Enable IMDsv2

- modules/database/main.tf
- variables.tf
Fix to resolve duplicate tags issue in Aurora module.
> fix: Resolve duplicate tags issue

- data.tf
- modules/database/main.tf
This brings our RDS provider to version 7.7.1.
> feat: RDS/Aurora Provider Update

- modules/app_eks/iam-policy-docs.tf
> fix: Add cloudwatch metrics to policy

- modules/app_eks/iam-policy-docs.tf
- modules/app_eks/main.tf
- outputs.tf
Output creds to allow consumption by other modules.
> feat: Ouput db creds

- modules/secure_storage_connector/manual.md
> docs(secure-storage-connector): Adding manual instructions.

- modules/app_eks/main.tf
> fix: Fix desired_capacity value passing

- modules/app_eks/main.tf
> fix: Set min capacity = desired capacity

- main.tf
- variables.tf
Add passthrough env vars for weave, parquet, and gorilla.
> fix(dev): Add passthrough for env vars

- modules/app_eks/main.tf
This PR removes the desired_capacity parameter from the EKS module in favor of setting min_capacity.
> feat: Remove desired_capacity in favor of setting min_capacity

- main.tf
- modules/kms/main.tf
- modules/kms/outputs.tf
- modules/kms/variables.tf
- modules/networking/main.tf
- modules/networking/outputs.tf
- modules/networking/variables.tf
- outputs.tf
- variables.tf
Set up prerequisites for enabling CMEK in Clickhouse as well as support for AWS private link.
> feat: Set up KMS key for clickhouse CMEK and endpoint for PL

- main.tf
This is not needed for our current setup
> fix: Cleanup unneeded otel configs

- modules/app_eks/main.tf
Switch to GP3 EBS volumes by default
> feat: Add a new default storage class that uses GP3 for storage

- modules/app_eks/external_dns/external_dns.tf
AWS rate limiting fix of route 53
> fix: Rate limiting of aws R53

- main.tf
related: 
- https://github.com/wandb/console/pull/89
- https://github.com/wandb/helm-charts/pull/301
> feat: Add role passthrough

- examples/byo-vpc-sql/main.tf
- examples/byo-vpc-sql/variables.tf
- main.tf
- modules/app_eks/add-ons.tf
- modules/app_eks/variables.tf
- variables.tf
ref INFRA-268
Metrics server is needed for HPA.
> feat: Add metric-server

- README.md
- main.tf
- modules/app_eks/iam-policy-docs.tf
- modules/app_eks/variables.tf
- variables.tf
ref INFRA-326
closes INFRA-328
> feat: Allow flexible external bucket access

- main.tf
- modules/cloudtrail/main.tf
- modules/cloudtrail/outputs.tf
- modules/cloudtrail/variables.tf
- variables.tf
Adding an option to enable Cloudtrail logs for S3 read/write events
> feat: Cloudtrail logging for s3 events
